In [8]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils
import random
import array

import import_ipynb
from ThesisDataset import PlanningDataset

In [9]:
train_data = PlanningDataset(1000)
test_data = PlanningDataset(100)

print(type(train_data[0][0]))
print(train_data[0][0].shape)

batch_size = 4

trainloader = torch.utils.data.DataLoader(train_data, batch_size=batch_size,
                                          shuffle=True, num_workers=2)
testloader = torch.utils.data.DataLoader(test_data, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [

In [10]:
def show_batch(dl):
    """Plot images grid of single batch"""
    for images, labels in dl:
        print("image: ", images)
        print("labels: ", labels)
        
show_batch(trainloader)

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

labels:  tensor([[0.6607],
        [0.4680],
        [0.4132],
        [0.5926]])
image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]],


        [[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  .

In [11]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        # input channels, output no. of features, kernel size
        self.conv1 = nn.Conv2d(3, 6, 5)
#         self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 92 * 92, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 1)
#         self.double()

    def forward(self, x):
#         x = self.pool(F.relu(self.conv1(x)))
#         x = self.pool(F.relu(self.conv1(x)))
        
#         x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
     #   x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

In [12]:
print(net)

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=135424, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=1, bias=True)
)


In [13]:
import torch.optim as optim

#criterion = nn.CrossEntropyLoss()
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


In [15]:
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data
        
#         print(inputs[0])
        
        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        # REMEMBER TO ADD float()
        outputs = net(inputs.float())
        
        print("outputs: ", outputs)
        print("labels: ", labels)
        loss = criterion(outputs, labels)
        
        loss.backward()
        optimizer.step()
        
        # print statistics
        running_loss += loss.item()
        if i % 10 == 9:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 10))
            running_loss = 0.0

print('Finished Training')

outputs:  tensor([[0.5075],
        [0.5075],
        [0.5075],
        [0.5075]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.2235],
        [0.4972],
        [0.0797],
        [0.7246]])
outputs:  tensor([[0.5074],
        [0.5074],
        [0.5074],
        [0.5074]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1038],
        [0.4620],
        [0.7126],
        [0.5128]])
outputs:  tensor([[0.5061],
        [0.5061],
        [0.5061],
        [0.5061]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.9303],
        [0.6839],
        [0.5052],
        [0.8458]])
outputs:  tensor([[0.5095],
        [0.5095],
        [0.5095],
        [0.5095]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.7948],
        [0.2230],
        [0.6806],
        [0.5212]])
outputs:  tensor([[0.5135],
        [0.5135],
        [0.5135],
        [0.5135]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.2270],
        [0.6311],
        [0.4871],
        [0.8583]])
outputs:  tensor([[0.5178],
        [0.5178],
    

outputs:  tensor([[0.4885],
        [0.4885],
        [0.4885],
        [0.4885]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0348],
        [0.1702],
        [0.8085],
        [0.6870]])
outputs:  tensor([[0.4956],
        [0.4956],
        [0.4956],
        [0.4956]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.5606],
        [0.6922],
        [0.2920],
        [0.7502]])
outputs:  tensor([[0.5036],
        [0.5036],
        [0.5036],
        [0.5036]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.2540],
        [0.5058],
        [0.8216],
        [0.7720]])
outputs:  tensor([[0.5125],
        [0.5125],
        [0.5125],
        [0.5125]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.8539],
        [0.0290],
        [0.0615],
        [0.4570]])
outputs:  tensor([[0.5174],
        [0.5174],
        [0.5174],
        [0.5174]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.9584],
        [0.1829],
        [0.4252],
        [0.9683]])
outputs:  tensor([[0.5243],
        [0.5243],
    

outputs:  tensor([[0.5193],
        [0.5193],
        [0.5193],
        [0.5193]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1945],
        [0.7826],
        [0.4348],
        [0.0987]])
[1,    90] loss: 0.000
outputs:  tensor([[0.5131],
        [0.5131],
        [0.5131],
        [0.5131]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4744],
        [0.6361],
        [0.4142],
        [0.5923]])
outputs:  tensor([[0.5080],
        [0.5080],
        [0.5080],
        [0.5080]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0649],
        [0.9337],
        [0.1963],
        [0.0594]])
outputs:  tensor([[0.4998],
        [0.4998],
        [0.4998],
        [0.4998]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.7401],
        [0.2139],
        [0.6388],
        [0.1359]])
outputs:  tensor([[0.4915],
        [0.4915],
        [0.4915],
        [0.4915]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1807],
        [0.1132],
        [0.1986],
        [0.5114]])
outputs:  tensor([[0.4801],

outputs:  tensor([[0.4920],
        [0.4920],
        [0.4920],
        [0.4920]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.5011],
        [0.4072],
        [0.3629],
        [0.7769]])
outputs:  tensor([[0.4959],
        [0.4959],
        [0.4959],
        [0.4959]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.2052],
        [0.0972],
        [0.0819],
        [0.0466]])
outputs:  tensor([[0.4930],
        [0.4930],
        [0.4930],
        [0.4930]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4677],
        [0.8511],
        [0.1700],
        [0.7623]])
outputs:  tensor([[0.4916],
        [0.4916],
        [0.4916],
        [0.4916]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.8866],
        [0.2072],
        [0.4612],
        [0.0325]])
outputs:  tensor([[0.4887],
        [0.4887],
        [0.4887],
        [0.4887]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.7551],
        [0.7567],
        [0.5961],
        [0.4229]])
outputs:  tensor([[0.4885],
        [0.4885],
    

outputs:  tensor([[0.4652],
        [0.4652],
        [0.4652],
        [0.4652]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0854],
        [0.7959],
        [0.7504],
        [0.4954]])
outputs:  tensor([[0.4648],
        [0.4648],
        [0.4648],
        [0.4648]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.2879],
        [0.5512],
        [0.4974],
        [0.1396]])
[1,   180] loss: 0.000
outputs:  tensor([[0.4630],
        [0.4630],
        [0.4630],
        [0.4630]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1942],
        [0.1220],
        [0.5271],
        [0.3394]])
outputs:  tensor([[0.4590],
        [0.4590],
        [0.4590],
        [0.4590]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4141],
        [0.1257],
        [0.9671],
        [0.9138]])
outputs:  tensor([[0.4575],
        [0.4575],
        [0.4575],
        [0.4575]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.3311],
        [0.8877],
        [0.4203],
        [0.1094]])
outputs:  tensor([[0.4559],

outputs:  tensor([[0.5751],
        [0.5751],
        [0.5751],
        [0.5751]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.8953],
        [0.0899],
        [0.2774],
        [0.6262]])
outputs:  tensor([[0.5802],
        [0.5802],
        [0.5802],
        [0.5802]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.5513],
        [0.4756],
        [0.9785],
        [0.2749]])
outputs:  tensor([[0.5845],
        [0.5845],
        [0.5845],
        [0.5845]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.9002],
        [0.6233],
        [0.9174],
        [0.4822]])
outputs:  tensor([[0.5921],
        [0.5921],
        [0.5921],
        [0.5921]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0901],
        [0.8920],
        [0.5724],
        [0.2142]])
outputs:  tensor([[0.5952],
        [0.5952],
        [0.5952],
        [0.5952]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0891],
        [0.0892],
        [0.7038],
        [0.0198]])
outputs:  tensor([[0.5888],
        [0.5888],
    

outputs:  tensor([[0.4715],
        [0.4715],
        [0.4715],
        [0.4715]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4539],
        [0.1934],
        [0.2520],
        [0.1876]])
outputs:  tensor([[0.4714],
        [0.4714],
        [0.4714],
        [0.4714]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6567],
        [0.8812],
        [0.8925],
        [0.2842]])
outputs:  tensor([[0.4742],
        [0.4742],
        [0.4742],
        [0.4742]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1927],
        [0.6989],
        [0.4369],
        [0.8323]])
outputs:  tensor([[0.4777],
        [0.4777],
        [0.4777],
        [0.4777]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.8408],
        [0.5112],
        [0.0272],
        [0.9118]])
[2,    20] loss: 0.000
outputs:  tensor([[0.4822],
        [0.4822],
        [0.4822],
        [0.4822]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6033],
        [0.3316],
        [0.9621],
        [0.8321]])
outputs:  tensor([[0.4890],

outputs:  tensor([[0.5120],
        [0.5120],
        [0.5120],
        [0.5120]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6379],
        [0.0492],
        [0.7957],
        [0.5775]])
[2,    60] loss: 0.000
outputs:  tensor([[0.5133],
        [0.5133],
        [0.5133],
        [0.5133]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.7001],
        [0.1771],
        [0.0824],
        [0.2415]])
outputs:  tensor([[0.5110],
        [0.5110],
        [0.5110],
        [0.5110]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.7680],
        [0.6264],
        [0.0807],
        [0.0908]])
outputs:  tensor([[0.5071],
        [0.5071],
        [0.5071],
        [0.5071]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4985],
        [0.0680],
        [0.8303],
        [0.0484]])
outputs:  tensor([[0.5013],
        [0.5013],
        [0.5013],
        [0.5013]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0424],
        [0.1699],
        [0.2595],
        [0.8600]])
outputs:  tensor([[0.4936],

outputs:  tensor([[0.5136],
        [0.5136],
        [0.5136],
        [0.5136]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1374],
        [0.0025],
        [0.6079],
        [0.0460]])
outputs:  tensor([[0.5071],
        [0.5071],
        [0.5071],
        [0.5071]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6618],
        [0.3900],
        [0.5060],
        [0.6529]])
outputs:  tensor([[0.5020],
        [0.5020],
        [0.5020],
        [0.5020]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1664],
        [0.8993],
        [0.2461],
        [0.1689]])
outputs:  tensor([[0.4956],
        [0.4956],
        [0.4956],
        [0.4956]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6736],
        [0.5255],
        [0.6347],
        [0.2200]])
outputs:  tensor([[0.4902],
        [0.4902],
        [0.4902],
        [0.4902]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0825],
        [0.3115],
        [0.1504],
        [0.8534]])
outputs:  tensor([[0.4834],
        [0.4834],
    

outputs:  tensor([[0.5122],
        [0.5122],
        [0.5122],
        [0.5122]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.3936],
        [0.7198],
        [0.0993],
        [0.5602]])
[2,   150] loss: 0.000
outputs:  tensor([[0.5114],
        [0.5114],
        [0.5114],
        [0.5114]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4993],
        [0.3968],
        [0.6777],
        [0.5437]])
outputs:  tensor([[0.5110],
        [0.5110],
        [0.5110],
        [0.5110]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6123],
        [0.1840],
        [0.8512],
        [0.5481]])
outputs:  tensor([[0.5112],
        [0.5112],
        [0.5112],
        [0.5112]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.1071],
        [0.4238],
        [0.4552],
        [0.3840]])
outputs:  tensor([[0.5089],
        [0.5089],
        [0.5089],
        [0.5089]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.0703],
        [0.1861],
        [0.1200],
        [0.0141]])
outputs:  tensor([[0.5006],

outputs:  tensor([[0.4893],
        [0.4893],
        [0.4893],
        [0.4893]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.4164],
        [0.2194],
        [0.2976],
        [0.4976]])
outputs:  tensor([[0.4855],
        [0.4855],
        [0.4855],
        [0.4855]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.5946],
        [0.8470],
        [0.3772],
        [0.1173]])
outputs:  tensor([[0.4821],
        [0.4821],
        [0.4821],
        [0.4821]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6656],
        [0.3842],
        [0.3504],
        [0.6603]])
outputs:  tensor([[0.4795],
        [0.4795],
        [0.4795],
        [0.4795]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.5613],
        [0.9998],
        [0.5478],
        [0.4583]])
outputs:  tensor([[0.4792],
        [0.4792],
        [0.4792],
        [0.4792]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.6383],
        [0.4466],
        [0.7409],
        [0.9213]])
outputs:  tensor([[0.4816],
        [0.4816],
    

outputs:  tensor([[0.4381],
        [0.4381],
        [0.4381],
        [0.4381]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.8238],
        [0.4851],
        [0.6393],
        [0.8983]])
[2,   240] loss: 0.000
outputs:  tensor([[0.4449],
        [0.4449],
        [0.4449],
        [0.4449]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.5729],
        [0.3487],
        [0.5355],
        [0.6608]])
outputs:  tensor([[0.4521],
        [0.4521],
        [0.4521],
        [0.4521]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.8581],
        [0.1827],
        [0.8911],
        [0.4494]])
outputs:  tensor([[0.4602],
        [0.4602],
        [0.4602],
        [0.4602]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.7093],
        [0.6441],
        [0.7039],
        [0.7435]])
outputs:  tensor([[0.4704],
        [0.4704],
        [0.4704],
        [0.4704]], grad_fn=<AddmmBackward>)
labels:  tensor([[0.9297],
        [0.9403],
        [0.2889],
        [0.6307]])
outputs:  tensor([[0.4826],