In [3]:
import random

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

In [4]:
def get_z(n):
    out = np.eye(n, dtype=np.int)
    out[[0,-1]] = 1
    return out[::-1]

example = get_z(2)
print(example)

# def get_z(n):
#     return np.zeros((n, n), dtype=int)

# sample = get_z(5)
# print(sample)

[[1 1]
 [1 1]]


In [5]:
# Create partial images

def get_partial_images(list_length):
    partial_images = list()

    for _ in range(list_length):

        partial_image = list()

        for _ in range(3):
            #initial = np.ndarray.copy(get_z(5))
            binary_matrix = get_z(10)
            print(binary_matrix)
            #You get a negative stride (PyTorch word) if you don't apply np.flip()
#             partial_image.append(torch.from_numpy(np.flip(binary_matrix,axis=0).copy()))
            partial_image.append((np.flip(binary_matrix,axis=0).copy()))
#             partial_images.append(np.flip(binary_matrix,axis=0).copy())

        #partial_images.append(torch.IntTensor(partial_image).unsqueeze(0))
        partial_images.append(torch.IntTensor(partial_image))
                              
    return partial_images

In [6]:
paths = get_partial_images(1)
print(paths[0])
print(type(paths[0]))
print(paths[0].shape)

[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]]
tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0

In [34]:
# Create paths

def get_paths(list_length):
    paths = list()

    for _ in range(list_length): # This range should be len(partial_images)
        binary_matrix = get_z(5)
        #paths.append(torch.from_numpy(np.flip(binary_matrix,axis=0).copy()))
        paths.append(np.flip(binary_matrix,axis=0).copy())
        
    return torch.IntTensor(paths)

In [35]:
paths = get_paths(1)
print(paths)
# print(paths.shape)

tensor([[[1, 1, 1, 1, 1],
         [0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 0, 0, 1, 0],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)


In [36]:
# Create actions

def get_actions(list_length):
    actions = list()

    for _ in range(list_length):

        action = list()

        for _ in range(3):
            binary_matrix = get_z(5)
            action.append(torch.from_numpy(np.flip(binary_matrix,axis=0).copy()))

        actions.append(action)

    return actions

In [37]:
paths = get_partial_images(1)
print(paths)
print(type(paths[0]))
print(paths[0].shape)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[tensor([[[1, 1, 1,  ..., 1, 1, 1],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [1, 1, 1,  ..., 1, 1, 1]],

        [[1, 1, 1,  ..., 1, 1, 1],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [1, 1, 1,  ..., 1, 1, 1]],

        [[1, 1, 1,  ..., 1, 1, 1],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0]

In [38]:
class PlanningDataset(Dataset):
    def __init__(self, list_length):
        self.partial_images = get_partial_images(list_length)
#         self.paths = get_paths(list_length)
#         self.actions = get_actions(list_length) 
        self.list_length = list_length

    def __len__(self):
        return self.list_length

    def __getitem__(self, idx): 
#         sample = [[self.partial_images[idx], self.paths[idx], self.actions[idx]], random.randrange(0, 9)]
        sample = self.partial_images[idx], torch.Tensor([random.random()]).float()

        return sample

In [39]:
dataset = PlanningDataset(1)
print(dataset[0][1])
print(type(dataset[0][1]))

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
tensor([0.0650])
<class 'torch.Tensor'>


In [40]:
dataloader = DataLoader(dataset, batch_size=1,
                        shuffle=True, num_workers=0)



In [41]:
def show_batch(dl):
    """Plot images grid of single batch"""
    for images, labels in dl:
        print("image: ", images)
        print("labels: ", labels)
        
show_batch(dataloader)

image:  tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]],

         [[1, 1, 1,  ..., 1, 1, 1],
          [0, 1, 0,  ..., 0, 0, 0],
          [0, 0, 1,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 1, 0, 0],
          [0, 0, 0,  ..., 0, 1, 0],
          [1, 1, 1,  ..., 1, 1, 1]]]], dtype=torch.int32)
labels:  tensor([[0.0341]])
